addressing common error of missing reset function
AttributeError: 'Sequential' object has no attribute 'reset' addressed by simpli adding a reset function call to return self.start()